USE PASSRLY;
DROP TABLE MSTRAILWAYSTATION;
CREATE TABLE MSTRAILWAYSTATION
(NRSID INT PRIMARY KEY,
CODE VARCHAR(5),
NAME VARCHAR(20),
LINE VARCHAR(20),
ISACTIVE INT
);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (001,'PL','PANVEL','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (002,'KNDS','Khandeshwar','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (003,'MANR','Mansarovar','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (004,'KHAG','Kharghar','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (005,'BR','CBD Belapur','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (006,'SWDV','Seawoods-Darave','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (007,'NU','Nerul','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (008,'JNJ','Juinagar','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (009,'SNCR','Sanpada','HARBOR',1);
INSERT INTO MSTRAILWAYSTATION(NRSID,CODE,NAME,LINE,ISACTIVE)
VALUES (010,'VA','Vashi','HARBOR',1);
SELECT * from MSTRAILWAYSTATION;
DROP TABLE MSTSTREAM;
CREATE TABLE MSTSTREAM
(SSMID INT PRIMARY KEY,
SSMNAME VARCHAR(50),
SSMSHORT VARCHAR(5),
ISACTIVE INT
);
INSERT INTO MSTSTREAM(SSMID,SSMNAME,SSMSHORT)
VALUES (001,'INFORMATION TECHNOLOGY','INFT');

DROP TABLE MGENDER;
CREATE TABLE MGENDER
(
GMID INT PRIMARY KEY,
GENDERTYPE VARCHAR(20),
ISACTIVE INT
);
INSERT INTO MGENDER(GMID,GENDERTYPE,ISACTIVE)
VALUES (001,'MALE',1);
INSERT INTO MGENDER(GMID,GENDERTYPE,ISACTIVE)
VALUES (002,'FEMALE',1);
INSERT INTO MGENDER(GMID,GENDERTYPE,ISACTIVE)
VALUES (003,'TRANSGENDER',1);
SELECT * FROM MGENDER;

DROP TABLE MREGISTRATIONYEAR;
CREATE TABLE MREGISTRATIONYEAR
(
RYMID INT PRIMARY KEY,
REGISTRATIONYEAR INT,
ISACTIVE INT
);
INSERT INTO MREGISTRATIONYEAR(RYMID,REGISTRATIONYEAR,ISACTIVE)
VALUES (001,2021,1);
SELECT * FROM MREGISTRATIONYEAR;

DROP TABLE MPASSTYPE;
CREATE TABLE MPASSTYPE
(
PTID INT,
TYPE VARCHAR(20),
ISACTIVE INT
);
INSERT INTO MPASSTYPE(PTID,TYPE,ISACTIVE)
VALUES (001,'FIRST CLASS',1);
INSERT INTO MPASSTYPE(PTID,TYPE,ISACTIVE)
VALUES (002,'SECOND CLASS',1);
SELECT * FROM MPASSTYPE;

DROP TABLE MPAYMENTMODE;
CREATE TABLE MPAYMENTMODE
(
PAYMODEID INT,
PAYMODE VARCHAR(20),
ISACTIVE INT
);
INSERT INTO MPAYMENTMODE(PAYMODEID,PAYMODE,ISACTIVE)
VALUES (001,'CREDIT CARD',1);
INSERT INTO MPAYMENTMODE(PAYMODEID,PAYMODE,ISACTIVE)
VALUES (002,'DEBIT CARD',1);
INSERT INTO MPAYMENTMODE(PAYMODEID,PAYMODE,ISACTIVE)
VALUES (003,'UPI',1);
INSERT INTO MPAYMENTMODE(PAYMODEID,PAYMODE,ISACTIVE)
VALUES (004,'CASH',1);
SELECT * FROM MPAYMENTMODE;
DROP TABLE DB_Errors;
CREATE TABLE DB_Errors
         (ErrorID        INT IDENTITY(1, 1),
          UserName       VARCHAR(100),
          ErrorNumber    INT,
          ErrorState     INT,
          ErrorSeverity  INT,
          ErrorLine      INT,
          ErrorProcedure VARCHAR(MAX),
          ErrorMessage   VARCHAR(MAX),
          ErrorDateTime  DATETIME);
GO
select * from DB_Errors;





